######################## default configuration ####################
baseURL = "https://owcf-test.github.io"
title = "Ocean Waste Catcher Foundation"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
#disqusShortname = "owcf" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["En"] # disable language from here

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

############################## navigation ###############################

[[menu.main]]
name = "Idea"
URL = "../idea"
weight = 1

[[menu.main]]
weight = 2
name = "Project"
hasChildren = true

  [[menu.main]]
  parent = "Project"
  name = "capital"
  URL = "../capital"
  weight = 10

  [[menu.main]]
  parent = "Project"
  name = "timeline"
  URL = "../timeline"
  weight = 20

  [[menu.main]]
  parent = "Project"
  name = "founder"
  URL = "../founder"
  weight = 30

  [[menu.main]]
  parent = "Project"
  name = "../Advisary Council"
  URL = "council"
  weight = 40
  
[[menu.main]]
name = "Blog"
URL = "../blog"
weight = 3
  
[[menu.main]]
name = "Donate"
URL = "../donate"
weight = 4

[[menu.main]]
name = "Contact"
URL = "../contact"
weight = 5

# footer menu
[[menu.footer]]
name = "imprint"
URL = "../imprint"

[[menu.footer]]
name = "privacy notice"
URL = "../notice"

#################### default parameters ################################
[params]

logo = "images/logo.png"

# Meta data
description = "Ocean Waste Catcher Foundation e.V"
author = "Themefisher"
# contact info
address = "Isegrimsteig 33, D-13503 Berlin-Heiligensee"
mobile = "+49 179 811 5385"
email = "N.Oefner@ocean-waste-catcher-foundation.com"
# contact form action
contact_form_action = "https://formsubmit.co/af17e387d32f368d43c0aa74acfa6d8f" # contact form works with https://formspree.io, free alternative: https://formsubmit.co/help
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true
donate = "Spendenkonto:  BIC:  NOLADE21KIE -  IBAN: DE55 2105 0170 1003 6951 27 -  Stichwort: Ocean waste catcher e.V."

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
#gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
#map_latitude = "51.5223477"
#map_longitude = "-0.1622023"
#map_marker = "images/marker.png"
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://de-de.facebook.com/UNICEFdeutschland" #TODO replace with owc homepage!

#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "instagram"
#icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "github"
#icon = "ti-github" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"

################################### French language #####################################

[Languages.de]
languageName = "De"
languageCode = "de-de"
contentDir = "content/german"
weight = 1
home = "Home"
idea = "Idee"

# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"

[[Languages.de.menu.main]]
url    = "../idea"
name   = "Idee"
weight = 1

[[Languages.de.menu.main]]
url    = "#"
name   = "Projekt"
weight = 2

    [[Languages.de.menu.main]]
    parent = "Projekt"
    url    = "../capital"
    name   = "Kapital"
    weight = 10

    [[Languages.de.menu.main]]
    parent = "Projekt"
    url    = "../timeline"
    name   = "Zeitplan"
    weight = 20

    [[Languages.de.menu.main]]
    parent = "Projekt"
    url    = "../founder"
    name   = "Gründer"
    weight = 30

    [[Languages.de.menu.main]]
    parent = "Projekt"
    url    = "../council"
    name   = "Beirat"
    weight = 40

[[Languages.de.menu.main]]
url    = "../blog"
name   = "Blog"
weight = 3

[[Languages.de.menu.main]]
url    = "../donate"
name   = "Spenden"
weight = 4

[[Languages.de.menu.main]]
url    = "../contact"
name   = "Kontakt"
weight = 5

# footer menu
[[Languages.de.menu.footer]]
name = "Impressum"
URL = "../imprint"

[[Languages.de.menu.footer]]
name = "Datenschutz"
URL = "../notice"

################################### English language #####################################

[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
idea = "Idea"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
